## Difference Formulas

```{python}
#| echo: false
import copy
import matplotlib.pyplot as plt
import numpy as np
import scipy
import seaborn as sns
```

In this section, formulas for approximating derivatives by forming differences of func values are introduced. These formulas are all based on the Taylor expansion and can be formulated for arbitrary derivatives and orders. The simplest ones are presented here.

### First Derivative, First Order

The simplest difference formula is obtained from the Taylor series up to $\mathsf{\mathcal{O}(h^2)}$. Here, the series can be directly rearranged for the desired derivative at the point $\mathsf{x_0}$.

$$\mathsf{f(x_0 + h) = f(x_0) + f'(x_0)h + \mathcal{O}(h^2)} $$
$$\mathsf{\Rightarrow \quad f'(x_0) = \frac{f(x_0 + h) - f(x_0)}{h} + \mathcal{O}(h)} $$

This is the forward difference formula of first order for the first derivative.  
First order means that in the limit $\mathsf{h\rightarrow 0}$ the approximation error decreases linearly with the step size.

According to this formula, the func to be differentiated must be evaluated at two points $\mathsf{f(x_0)}$ and $\mathsf{f(x_0+h)}$ in order to determine the derivative numerically. In the limit of an arbitrarily small step size, i.e. $\mathsf{h \rightarrow 0}$, this quotient approaches the exact derivative at the point $\mathsf{x_0}$.

The following example demonstrates the approximation using the func

$$ \mathsf{f(x) = \sin(3x) + 2x} $$

The derivative is approximated at the point $\mathsf{x_0 = 0.85}$.

```{python}
def func(x):
    return np.sin(3*x) + 2*x

# Data for visualization
x = np.linspace(0, 2, 100)
y = func(x)

# Exact solution at x=0.85
fp_exactly = 3*np.cos(3*0.85) + 2
```










```{python}
# Expansion point and step size
h = 0.25
x0 = 0.85

# Evaluation at the two points
f0 = func(x0)
fh = func(x0 + h)

# Determination of the derivative approximation
fp = (fh - f0) / h
```

```{python}
print(f"The numerical approximation of the derivative at the point {x0:.2f}:")
print(f"Approximation with step size {h:.2f}: {fp:.2f}")
print(f"Exact value: {fp_exactly:.2f}")
```

The method can also be illustrated graphically. The desired slope is the slope of the straight line shown in the plot.

```{python}
#| tags: [hide_input]
plt.plot(x, y, label="Function")
plt.scatter([x0], [f0], color='C3', label='Expansion point', zorder=3)
plt.scatter([x0+h], [fh], color='C4', label='Evaluation points', zorder=3)

plt.vlines(x0, ymin=0, ymax=f0, color='C3', alpha=0.5)

plt.plot(x, f0 + fp*(x-x0), label='Difference formula')

plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.legend(bbox_to_anchor=(1.05, 1.0), loc='upper left');
```


### Second-Order First Derivative

Using the same approach, a second-order difference formula can also be derived. For this, the func is approximated at the points $\mathsf{x_0-h}$ and $\mathsf{x_0+h}$ using the Taylor series up to order $\mathsf{\mathcal{O}(h^3)}$.

$$\mathsf{f(x_0+h) = f(x_0) + f'(x_0)\cdot h + \frac{1}{2}f''(x_0)\cdot h^2 + \mathcal{O}(h^3)} $$
$$\mathsf{f(x_0-h) = f(x_0) - f'(x_0)\cdot h + \frac{1}{2}f''(x_0)\cdot h^2 + \mathcal{O}(h^3)} $$

The difference between these two equations gives

$$\mathsf{f(x_0+h) - f(x_0-h) = 2f'(x_0)\cdot h + \mathcal{O}(h^3)} $$

Rearranging for the derivative at the point $\mathsf{x_0}$ yields

$$\mathsf{f'(x_0) = \frac{f(x_0+h) - f(x_0-h)}{2h} + \mathcal{O}(h^2)} $$

This is the central difference formula for the first derivative with second-order accuracy. As with the forward formula, the func must be evaluated at two points, but not at the expansion point itself. This symmetry around the expansion point results in improved convergence behavior, which is quadratic in this case.

```{python}
# Evaluate the func at both points
fmh = func(x0 - h)
fph = func(x0 + h)

# Compute the derivative approximation
fp = (fph - fmh) / (2*h)
```








```{python}
print(f"The numerical approximation of the derivative at the point {x0:.2f}:")
print(f"Approximation with step size {h:.2f}: {fp:.2f}")
print(f"Exact value: {fp_exactly:.2f}")
```

The method can also be represented graphically. The slope sought is the slope of the straight lines drawn.

```{python}
#| tags: [hide_input]
plt.plot(x, y, label="Function")
plt.scatter([x0], [f0], color='C3', label='Expansion Point', zorder=3)
plt.scatter([x0-h, x0+h], [fmh, fph], color='C4', label='Evaluation Points', zorder=3)

plt.vlines(x0, ymin=0, ymax=f0, color='C3', alpha=0.5)

plt.plot(x, fmh + fp*(x-x0+h), label='Difference Formula')

plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.legend(bbox_to_anchor=(1.05, 1.0), loc='upper left');
```


## Second-Order Derivative

Using the same scheme as above, the finite difference formula for the second derivative can also be determined. It is given by

$$\mathsf{f''(x_0) = \frac{f(x_0-h) - 2f(x_0) + f(x_0+h)}{h^2} + \mathcal{O}(h^2)}$$